apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -w1

patches:
  - target:
      kind: Pod
      name: echo-server
    patch: |
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER
  - target:
      kind: Pod
      name: client
    patch: |
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER
