apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Pod
      name: echo-server
    patch: |
      - op: replace
        path: /metadata/name
        value: echo-server-w1
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER
  - target:
      kind: Pod
      name: client
    patch: |
      - op: replace
        path: /metadata/name
        value: client-w1
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER