apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
  labels:
    app: iperf3
    role: client
spec:
  containers:
  - name: iperf3
    image: quay.io/networkstatic/iperf3:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c"]
    args: ["sleep infinity"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
