apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Pod
      name: fortio-server
    patch: |
      - op: replace
        path: /metadata/name
        value: fortio-server-w2
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER
  - target:
      kind: Pod
      name: fortio-client
    patch: |
      - op: replace
        path: /metadata/name
        value: fortio-client-w2
      - op: add
        path: /spec/nodeName
        value: NODE_NAME_PLACEHOLDER
